<style type="text/css">
#container {
  font-family: 'Poppins';
	padding: 15px;
}
#container p {
	text-align: justify;
	text-indent: 40px;
}
#container > h1 {
  text-align: center;
}
#contents {
  display: grid;
  grid-template-columns: repeat(auto-fit, 200px);
  grid-auto-rows: 200px;
  justify-content: center;
  grid-gap: 25px;
  width: 100%;
}
#contents a {
  font-weight: 700;
  text-align: center;
  display: block;
  color: black;
  align-items: center;
  background-color: var(--opposite);
  box-shadow: 0 0 1rem #0003;
  transition: 0.3s;
  padding: auto;
  border-radius: 5px; /* 5px rounded corners */
  font-size: 20pt;
}
#contents a i {
  font-size: 7rem;
  display: block;
  margin: 0;
}
</style>
<div id="container">
	<h1>Contents</h1>
	<div id="contents">
	  <a href="/game">
	    <i>&#xf11b;</i>
		  <span>Game</span>
	  </a>
	  <a>
	    <i>&#xe804;</i>
		  <span>Art</span>
	  </a>
	  <a>
	    <i>&#xe806;</i>
		  <span>Informations</span>
	  </a>
	  <a>
	    <i>&#xe805;</i>
		  <span>None</span>
	  </a>
	  <a>
	    <i>&#xf0ae;</i>
		  <span>Task</span>
	  </a>
	</div>
</div>

