<style>
  footer {
    display: block;
    padding: 30px;
    background: #0008;
    font-size: 20pt;
  }
  footer div {
    display: block;
    text-align: center;
    align-items: center;
    justify-content: center;
  }
  footer div a i {
    width: 2em;
    height: 2em;
    display: table-cell;
    text-align: center;
    vertical-align: middle;
    border-radius: 50%;
    border: 0.01em solid;
  }
  footer p {
    display: block;
    font-size: 1em;
    text-align: center;
  }
  /* while screen short */
  @media screen and (max-width: 800px) {
    footer div {
    	display: block;
    }
  }
</style>
<footer>
  <div>
    <h4>Other</h4>
    <a href="/about"><p>About Me</p></a>
    <a href="/updates"><p>Updates</p></a>
	</div>
  <div>
		<h4>Author</h4>
		<a href="mailto:ikomangwidiadaariasa12@gmail.com"><i>&#xe802;</i></a>
		<a href="https://github.com/AriasaProp"><i>&#xe80a;</i></a>
  </div>
	<p id="last-update">Update Now</p>
	<p>Made for fun!</p>
</footer>