<style>
#header {
  display: block;
  height: 150px;
}
#container {
  margin: 5px;
}
#container h1 {
	text-align: center;
}

#themeCntr {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
  padding: 15px;
  margin: 1rem;
  background-color: #3337;
  box-shadow: 0 0 5px #3337;
  border-radius: 15px;
}
#themeCntr input {
  text-align: center;
  margin: 15px;
  width: 75px;
  height: 75px;
  display: inline-block;
  position: relative;
  color: var(--fontColor);
}
#themeCntr input:before {
  content: '';
  width: 75px;
  height: 75px;
  border-radius: 37.5px;
  display: inline-block;
  position: relative;
  background-color: var(--tmc, white);
  border: 2px solid transparent;
}
#themeCntr input:checked:before {
  font-family: "main-icons";
  font-style: normal;
  font-size: 25pt;
  border: 3px solid;
  speak: never;
  font-variant: normal;
  text-transform: none;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  
  content: '\e807';
  text-align: right;
}
#graphicsQuality {
  margin: 5px;
  display: flex;
}
#graphicsQuality input[type="range"] {
  flex-grow: 1;
}

@media screen and (prefers-color-scheme: dark) {
  #themeCntr input {
    color: var(--fontColorDark);
  }
  #themeCntr input:before {
    background-color: var(--tmcd, black);
  }
}
</style>
<div id="container">
	<h1>Preferences</h1>
	<h3>Theme : </h3>
	<div id="themeCntr">
	  <template>
		  <input type="radio" name="themeopt" onclick="setThemeVar(this.value)"></input>
	  </template>
	</div>
	<br>
	<h3>Game : </h3>
	<form id="graphicsQuality">
	  Quality : 
	  <input id="graph_quality" name="range_quality" min="0" max="3" type="range"/>
	  <button type="submit">Set</button>
	</div>
</div>
<script id="theme-data" type="application/json">
[
  "#b3b3b3#efefef#eeeeee#000000#121212#262626#cccccc#f2f2f2",
  "#bebeff#ccccff#ffffee#000022#00008b#000040#cccc00#e6e6ff",
  "#b3ffb3#ccffcc#ffeeff#002200#006400#004000#cc00cc#e6ffe6",
  "#ffb3b3#ffcccc#eeffff#220000#b71c1c#400000#00cccc#ffe6e6",
  "#e299ff#f8e6ff#e6b3cc#13001a#9b3cc3#3e184e#d279a6#f5ecf9"
]
</script>
<script type="text/javascript" defer>
function setGraphQuality() {
  
}
function setThemeVar(key) {
  if(localStorage.getItem('theme') === key) return
  localStorage.setItem('theme', key)
  updateStyling()
}

var curTheme = localStorage.getItem("theme")
var themeData = JSON.parse(document.getElementById("theme-data").textContent)
const cntr = document.getElementById("themeCntr")
const part = cntr.getElementsByTagName("template")[0].content
for (var i = 0; i < themeData.length; ++i) {
  let a = []
  for (let j = 0; j < themeData[i].length; ++j)
    a.push(themeData[i].substring(j*7, (j+1)*7))
  let clon = part.cloneNode(true)
  let chil = clon.children[0]
  cntr.appendChild(clon)
  chil.style.setProperty("--tmc", a[0])
  chil.style.setProperty("--tmcd", a[4])
  chil.value = themeData[i]
  if ((curTheme === null && i === 0) || (curTheme === themeData[i])) chil.defaultChecked = true
}

var graph_quality = localStorage.getItem("graph_quality") || 1
const igraph_quality = document.getElementById("graph_quality")
igraph_quality.value = igraph_quality;

</script>
