<style>
#header {
  display: block;
  height: 150px;
}
* {
	/*outline: 1px solid lightgreen;*/
}
#container {
}
#container h1 {
	text-align: center;
}

#card-list {
  display: block;
	padding: 35px;
}
#card-list container {
  display: block;
  font-size: 20pt;
  background-color: var(--opposite);
  border-radius: 1.5rem;
	padding: 1.5rem;
	margin: 2rem 0;
  box-shadow: 0 0 3px var(--opposite);
}
#card-list container header {
  font-size: 2rem;
  font-weight: 700;
}
#card-list container p {
  font-size: 0.8rem;
}
#card-list container article {
  font-size: 1.05rem;
  text-indent: 1.7rem;
}
</style>
<div id="container">
	<h1>Updates</h1>
	<section id="card-list">
	  <template>
		  <container>
  		  <header>0.0.0</header>
  		  <p>Update: Card Date</p>
  		  <article>Card informations that may wrapped</article>
		  </container>
	  </template>
	</section>
</div>
<script type="text/javascript">
const cardl = document.getElementById("card-list")
fetch("./data/updates.json").then(response => response.json())
  .then(updateList => {
    for(up of updateList) {
      let temp = cardl.getElementsByTagName("template")[0]
      let clon = temp.content.cloneNode(true)
      let ctnr = clon.children[0]
      ctnr.getElementsByTagName("header")[0].innerHTML = up.version
      ctnr.getElementsByTagName("p")[0].innerHTML = up.date
      ctnr.getElementsByTagName("article")[0].innerHTML = up.comment
      cardl.appendChild(clon)
    }
  })
  .catch(error => {
    console.error('Get some error:', error);
  });
</script>
