<style>
  body {
  	background-size: 5000px;
  	background-position: right center;
  }
  main {
    margin: 10px;
  }
  main h1 {
    text-align: center;
  }
  main p {
    text-indent: 45px;
    font-size: 0.65em;
    text-align: justify;
  }
</style>
<main>
	<h3>About Me</h3>
	<p>
		I am by no means an expert in full-stack web development. I also have no background in programming or any knowledge of server technology whatsoever. Whether it"s my educational background, courses, or acquaintances, I have no one with a deep understanding of web development.
	</p>
	<p>
		My goal in creating this web design is to apply various information related to web development implementation, including HTML, CSS, JavaScript, and more. My practice in this field is still quite limited. Currently, I only work on it in my spare time as an additional hobby.
	</p>
	<p>
		Thank you for visiting my "About Me" page. I"m thrilled to share my journey, experiences, and insights with you through this blog. Feel free to reach out if you have any questions or would like to share your thoughts. I hope you enjoy the content on my blog. I greatly appreciate any feedback and criticism. That"s all for now.
	</p>
</main>