<style>
  body {
  	background-size: 3500px;
  	background-position: right top;
  }
  main {}
  main h1 {
  	text-align: center;
  }
  main div {
    display: block;
    justify-content: center;
    align-items: center;
  	text-align: center;
    padding: 15px;
    background-color: #3337;
    box-shadow: 0 0 5px #3337;
    border-radius: 15px;
    margin: 25px;
  }
  main div input[type='radio'] {
    text-align: center;
    align-items: center;
    margin: 4px;
    width: 45px;
    height: 45px;
    display: inline-block;
    position: relative;
  }
  main div input[type='radio']:before {
    content: '';
    width: 100%;
    height: 100%;
    border-radius: 50%;
    display: block;
  }
  main div input[type='radio']:nth-child(2):before {
	  background-color: #b3b3b3;
  }
  main div input[type='radio']:nth-child(3):before {
	  background-color: #bebeff;
  }
  main div input[type='radio']:nth-child(4):before {
	  background-color: #b3ffb3;
  }
  main div input[type='radio']:nth-child(5):before {
	  background-color: #ffb3b3;
  }
  main div input[type='radio']:nth-child(6):before {
	  background-color: #e299ff;
  }
  main div input[type='radio']:checked:after {
    content: '\e805';
    color: var(--font);
    font-family: 'ic';
    display: block;
    position: absolute;
    right: 0;
    top: 0;
    font-size: 25px;
  }
  min div h5 {
    display: block;
  }
  min div p {
    display: inline;
  }
  min div input[type='range'] {
    display: inline;
  }
  
  @media screen and (prefers-color-scheme: dark) {
    main div input[type='radio']:nth-child(2):before {
  	  background-color: #121212;
    }
    main div input[type='radio']:nth-child(3):before {
  	  background-color: #00008b;
    }
    main div input[type='radio']:nth-child(4):before {
  	  background-color: #006400;
    }
    main div input[type='radio']:nth-child(5):before {
  	  background-color: #b71c1c;
    }
    main div input[type='radio']:nth-child(6):before {
  	  background-color: #9b3cc3;
    }
  }
</style>
<main>
	<h3>Preferences</h3>
	<div>
	  <h5>Color</h5>
	  <?php
	  ?>
	  <input type="radio" name="themeopt"
  	  value="#b3b3b3#efefef#eee#000#121212#262626#ccc#f2f2f2"
  	  onchange='setColorsVar(this.value)'/>
	  <input type="radio" name="themeopt"
	    value="#bebeff#ccf#ffe#002#00008b#000040#cc0#e6e6ff"
  	  onchange='setColorsVar(this.value)'/>
	  <input type="radio" name="themeopt"
  	  value="#b3ffb3#cfc#fef#020#006400#004000#c0c#e6ffe6"
  	  onchange='setColorsVar(this.value)' />
	  <input type="radio" name="themeopt"
	    value="#ffb3b3#fcc#eff#200#b71c1c#400000#0cc#ffe6e6"
  	  onchange='setColorsVar(this.value)' />
	  <input type="radio" name="themeopt"
  	  value="#e299ff#f8e6ff#e6b3cc#13001a#9b3cc3#3e184e#d279a6#f5ecf9"
	    onchange='setColorsVar(this.value)'/>
	</div>
	<div>
	  <h5>Font Size</h5>
	  <p style="font-size: 10pt;">A</p>
	  <input id="fontSize-pref" value="12" type="range" min="10" max="18" step="1" onchange="setFontSizeVar(this.value)"/>
	  <p style="font-size: 18pt;">A</p>
	</div>
</main>
<script type="text/javascript">
  const tfz = localStorage.getItem('theme-fontSize');
  if(tfz) document.getElementById('fontSize-pref').value = tfz;
  const curColors = localStorage.getItem("theme-colors");
  if (curColors) {
    const radios = document.querySelectorAll('input[name="themeopt"]');
    radios.forEach(r => {
      r.defaultChecked = (r.value === curColors);
    });
  }
  function setColorsVar(key) {
    if(localStorage.getItem('theme-colors') !== key) {
      localStorage.setItem('theme-colors', key);
      updateColors();
    }
  }
  function setFontSizeVar(key) {
    if(localStorage.getItem('theme-fontSize') !== key) {
      localStorage.setItem('theme-fontSize', key);
      updateFontSize();
    }
  }
</script>