<style>
  body {
  	background-size: 3000px;
  	background-position: left top;
  }
  main {}
  main h1 {
  	text-align: center;
  }
  main ul {
    display: block;
  	padding: 35px;
  }
  main ul li {
  	text-align: left;
    display: block;
    background-color: var(--opposite);
    border-radius: 20px;
  	padding: 20px;
  	margin: 5px 0;
    box-shadow: 0 0 3px var(--opposite);
  }
  main ul li p {
    text-indent: 20px;
  }
</style>
<main>
	<h1>Updates</h1>
	<ul>
	  <li>
		  <h3>0.0.2</h3>
		  <p>Sep, 12 2024</p>
		  <p>New updates for test</p>
	  </li>
	  <li>
		  <h3>0.0.1</h3>
		  <p>Sep, 12 2023</p>
		  <p>New updates for test</p>
	  </li>
	  <li>
		  <h3>0.0.0</h3>
		  <p>Sep, 12 2022</p>
		  <p>First launch of website, nothing</p>
	  </li>
	</ul>
</main>